### ISSUE TITLE
buildx build fails with error `error: no valid drivers found:` for buildx version `0.5.0`

### ISSUE THREAD

**Issue by akhilerm** [docker/setup-buildx-action#45]
### Behaviour
When the github action is used as follows: 
```
        uses: docker/setup-buildx-action@v1
        with:
          version: latest
```
i.e with the latest version of buildx (0.5.0), the builds are failing with error. [Ref](https://github.com/akhilerm/node-disk-manager/runs/1555045310?check_suite_focus=true)
```
error: no valid drivers found: invalid driver option platform for docker-container driver
make: *** [docker.buildx] Error 1
```

This is the command that we executing and giving the above error
```
	export DOCKER_CLI_EXPERIMENTAL=enabled
	@if ! docker buildx ls | grep -q container-builder; then\
		docker buildx create --platform ${PLATFORMS} --name container-builder --use;\
	fi
	@docker buildx build --platform ${PLATFORMS} \
		-t "$(DOCKERX_IMAGE_NAME)" ${DBUILD_ARGS} -f $(PWD)/build/$(COMPONENT)/Dockerfile \
		. ${PUSH_ARG}
```

#### Steps to reproduce this issue

1. Use `setup-build-action` github action with latest buildx version (0.5.0)
2. Execute the following commands
```
if ! docker buildx ls | grep -q container-builder; then\
		docker buildx create --platform ${PLATFORMS} --name container-builder --use;\
fi
docker buildx build --platform ${PLATFORMS} \
		-t "$(DOCKERX_IMAGE_NAME)" ${DBUILD_ARGS} -f $(PWD)/build/$(COMPONENT)/Dockerfile \
		. ${PUSH_ARG}
```

#### Expected behaviour

> Tell us what should happen

The build process should continue without an error

#### Actual behaviour

> Tell us what happens instead
errors out with 
```
error: no valid drivers found: invalid driver option platform for docker-container driver
```

### Configuration

* Repository URL (if public):  https://github.com/akhilerm/node-disk-manager/tree/ci-test-action
* Build URL (if public): https://github.com/akhilerm/node-disk-manager/runs/1555045310?check_suite_focus=true

```yml
name: ci

on: ['push']

jobs:
  ndm-daemonset:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
        with:
          platforms: all

      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v1
        with:
          version: latest

      - name: Build Image
        env:
          IMG_RESULT: cache
        run: make docker.buildx.ndm
```

### Logs

> Download the [log file of your build](https://help.github.com/en/actions/configuring-and-managing-workflows/managing-a-workflow-run#downloading-logs) and [attach it](https://help.github.com/en/github/managing-your-work-on-github/file-attachments-on-issues-and-pull-requests) to this issue.
[logs_428.zip](https://github.com/docker/setup-buildx-action/files/5693635/logs_428.zip)

**Comment by tonistiigi** [comment]
I can't repro with

**Comment by tonistiigi** [comment]
I can't repro with
```
» docker buildx create --platform "linux/amd64,linux/arm64,linux/arm/v7,linux/ppc64le" --name container-builder --use                                                              
container-builder
```

**Comment by crazy-max** [comment]
@akhilerm Buildx v0.5.0 has been marked as pre-release in the meantime a fix is made so it should work with `version: latest` now (0.4.2).

**Comment by shubham14bajpai** [comment]
@tonistiigi I tried with 0.5.0 version locally and got the same error.
```sh
$ docker buildx build --platform linux/amd64 -t openebs/zfs-driver:ci -f dockerfile . --load
[+] Building 0.0s (0/0)                                                                                                                       
error: no valid drivers found: invalid driver option platform for docker-container driver
```

**Comment by crazy-max** [comment]
@shubham14bajpai Will me fixed in v0.5.1 of buildx (docker/buildx#475)

**Comment by tiborvass** [comment]
Closing, as v0.5.1 has been released https://github.com/docker/buildx/releases/tag/v0.5.1 :)

**Comment by macjl** [comment]
Still have the problem with current realease of docker-ce : 

```
$ docker version
Client: Docker Engine - Community
 Version:           20.10.1
 API version:       1.41
 Go version:        go1.13.15
 Git commit:        831ebea
 Built:             Tue Dec 15 04:34:48 2020
 OS/Arch:           linux/amd64
 Context:           default
 Experimental:      true

Server: Docker Engine - Community
 Engine:
  Version:          20.10.1
  API version:      1.41 (minimum version 1.12)
  Go version:       go1.13.15
  Git commit:       f001486
  Built:            Tue Dec 15 04:32:45 2020
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          1.4.3
  GitCommit:        269548fa27e0089a8b8278fc4fc781d7f65a939b
 runc:
  Version:          1.0.0-rc92
  GitCommit:        ff819c7e9184c13b7c2607fe6c30ae19403a7aff
 docker-init:
  Version:          0.19.0
  GitCommit:        de40ad0

$ docker buildx create --platform=linux/arm/v6,linux/arm/v7,linux/amd64 --use                                          hardcore_brown

$ docker buildx ls
NAME/NODE         DRIVER/ENDPOINT             STATUS PLATFORMS
hardcore_brown *  docker-container
  hardcore_brown0 unix:///var/run/docker.sock invalid driver option platform for docker-container driver
default           docker
  default         default                     running linux/amd64, linux/arm64, linux/riscv64, linux/ppc64le, linux/s390x, linux/386, linux/arm/v7, linux/arm/v6

```
How to upgrade ?

**Comment by elrik75** [comment]
On Debian Buster, Docker up to date and installed like this:
```
deb [arch=amd64] https://download.docker.com/linux/debian buster stable
```
I have buildx 0.5.0:
```
>$ docker buildx version
github.com/docker/buildx v0.5.0-docker 780fad46f23e8d7c2d741d59144617aae5285b22
```
So then I still have the `invalid driver option platform for docker-container driver` error

**Comment by shubham14bajpai** [comment]
@elrik75 This issue got fixed in 0.5.1. Try upgrading the buildx version using https://github.com/docker/buildx#installing

**Comment by macjl** [comment]
The problem came when docker-ce has been updated to v20.10.1. It included buildx v0.5.0, that have this bug.
It would be nice to publish a newer version of docker-ce whith buildx 0.5.1.

**Comment by tonistiigi** [comment]
@tiborvass ^
